import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

import { useEffect, useRef, useState } from "react";
import dynamic from "next/dynamic";

import { useDispatch, useSelector } from "react-redux";

const AvatarView = dynamic(() => import("@sarge/avatar-view"), {
  ssr: false,
});

export default function Home() {
  const router = useRouter();
  const dispatch = useDispatch();
  
  const {
    avatarUrl
  } = useSelector((state) => state);

  const [url, setUrl] = useState(null);

  useEffect(() => {
    setUrl(null);
    dispatch({ type: "setAvatarUrl", payload: "https://models.readyplayer.me/63f31c5c9233b3995d6a9563.glb" });
  }, []);
  
  useEffect(() => {
    setUrl(avatarUrl !== null && avatarUrl+'?morphTargets=eyesClosed,eyeSquintLeft,eyeSquintRight&useHands=false&textureAtlas=512&meshLod=2&morphTargets=eyesClosed,eyeSquintLeft,eyeSquintRight');
  }, [avatarUrl]);

  const options3DSetting = {
    faceTracking: false,
    orbitControl: false,
    followCursor: true,
    blinkEyes: true,
  };

  const options2DSetting = {
    scale: [1.4, 1.4],
    position: [0, -5],
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Ready Player Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.avartars}>
          <div className={styles.avatar}>
            <h2>3D</h2>
            <AvatarView
              style={{
                opacity: url === null ? 0 : 1,
                width: "150px",
                height: "150px",
                margin: "0 1rem",
                background: 'trasparent'
              }}
              type="3D"
              options3d={options3DSetting}
              url={`${url}`}
            />
          </div>

          <div className={styles.avatar}>
            <h2>2D</h2>
            <AvatarView
              style={{
                opacity: url === null ? 0 : 1,
                width: "150px",
                height: "150px",
                margin: "0 1rem",
              }}
              type="2D"
              options2d={options2DSetting}
              url={`${url}`}
            />
          </div>
        </div>

        <button onClick={() => router.push("/otherPage")}>
          go to other page
        </button>
      </main>
    </div>
  );
}
